### ISSUE TITLE
font-util installation fails in [spack] build of [nov20patches] on openSuse 15.2

### ISSUE THREAD

**Issue by TobiasStockmanns** [FairRootGroup/FairSoft#384] opened 2021-02-23 08:20 UTC
Here is the terminal output:
```
==> Installing font-util
==> No binary for font-util found: installing from source
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-encodings-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/encodings/encodings-1.0.4
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-alias-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-alias/font-alias-1.0.3
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-bh-ttf-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-bh-ttf/font-bh-ttf-1.0.3
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-bh-75dpi-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-bh-75dpi/font-bh-75dpi-1.0.3
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-bh-type1-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-bh-type1/font-bh-type1-1.0.3
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-dec-misc-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-dec-misc/font-dec-misc-1.0.3
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-jis-misc-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-jis-misc/font-jis-misc-1.0.3
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-sun-misc-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-sun-misc/font-sun-misc-1.0.3
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-bh-100dpi-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-bh-100dpi/font-bh-100dpi-1.0.3
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-ibm-type1-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-ibm-type1/font-ibm-type1-1.0.3
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-isas-misc-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-isas-misc/font-isas-misc-1.0.3
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-misc-misc-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-misc-misc/font-misc-misc-1.1.2
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-mutt-misc-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-mutt-misc/font-mutt-misc-1.0.3
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-micro-misc-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-micro-misc/font-micro-misc-1.0.3
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-adobe-75dpi-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-adobe-75dpi/font-adobe-75dpi-1.0.3
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-arabic-misc-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-arabic-misc/font-arabic-misc-1.0.3
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-cursor-misc-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-cursor-misc/font-cursor-misc-1.0.3
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-daewoo-misc-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-daewoo-misc/font-daewoo-misc-1.0.3
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-misc-meltho-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-misc-meltho/font-misc-meltho-1.0.3
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-adobe-100dpi-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-adobe-100dpi/font-adobe-100dpi-1.0.3
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-misc-cyrillic-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-misc-cyrillic/font-misc-cyrillic-1.0.3
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-misc-ethiopic-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-misc-ethiopic/font-misc-ethiopic-1.0.3
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-xfree86-type1-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-xfree86-type1/font-xfree86-type1-1.0.4
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-bitstream-75dpi-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-bitstream-75dpi/font-bitstream-75dpi-1.0.3
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-bitstream-type1-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-bitstream-type1/font-bitstream-type1-1.0.3
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-cronyx-cyrillic-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-cronyx-cyrillic/font-cronyx-cyrillic-1.0.3
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-schumacher-misc-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-schumacher-misc/font-schumacher-misc-1.1.2
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-screen-cyrillic-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-screen-cyrillic/font-screen-cyrillic-1.0.4
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-bitstream-100dpi-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-bitstream-100dpi/font-bitstream-100dpi-1.0.3
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-bitstream-speedo-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-bitstream-speedo/font-bitstream-speedo-1.0.2
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-winitzki-cyrillic-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-winitzki-cyrillic/font-winitzki-cyrillic-1.0.3
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-adobe-utopia-75dpi-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-adobe-utopia-75dpi/font-adobe-utopia-75dpi-1.0.4
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-adobe-utopia-type1-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-adobe-utopia-type1/font-adobe-utopia-type1-1.0.4
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-adobe-utopia-100dpi-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-adobe-utopia-100dpi/font-adobe-utopia-100dpi-1.0.4
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-bh-lucidatypewriter-75dpi-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-bh-lucidatypewriter-75dpi/font-bh-lucidatypewriter-75dpi-1.0.3
==> Moving resource stage
	source : /tmp/gitlab-runner/spack-stage/resource-font-bh-lucidatypewriter-100dpi-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/
	destination : /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-src/font-bh-lucidatypewriter-100dpi/font-bh-lucidatypewriter-100dpi-1.0.3
==> font-util: Executing phase: 'autoreconf'
==> font-util: Executing phase: 'configure'
==> font-util: Executing phase: 'build'
==> font-util: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
    './configure' '--prefix=/home/gitlab-runner/PandaSoftware/FairSoft/nov20/source/spack/opt/spack/linux-opensuse_leap15-skylake/gcc-7.5.0/font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3'

1 error found in build log:
     389    checking for mkfontdir... /home/gitlab-runner/PandaSoftware/FairSoft/nov20/source/spack/opt/spack/linux-opensuse_leap15-skylake/gcc-7.5.0/mkfontdir-1.0.7-gwy
            thlpcgvthyyw3aiq7lobckjjhqybr/bin/mkfontdir
     390    checking for bdftopcf... /home/gitlab-runner/PandaSoftware/FairSoft/nov20/source/spack/opt/spack/linux-opensuse_leap15-skylake/gcc-7.5.0/bdftopcf-1.0.5-byrc2
            pkq6m6dyfws3r2fooi5ssuwg23s/bin/bdftopcf
     391    checking font compression method... gzip
     392    checking for gzip... /usr/bin/gzip
     393    checking for ucs2any... /home/gitlab-runner/PandaSoftware/FairSoft/nov20/source/spack/opt/spack/linux-opensuse_leap15-skylake/gcc-7.5.0/font-util-1.3.2-c2kz5
            7gaz5zbahmxlya7ys52gttfuxl3/bin/ucs2any
     394    checking for MAPS... no
  >> 395    configure: error: Package requirements (fontutil) were not met:
     396
     397    Package 'fontutil', required by 'virtual:world', not found
     398
     399    Consider adjusting the PKG_CONFIG_PATH environment variable if you
     400    installed software in a non-standard prefix.
     401

See build log for details:
  /tmp/gitlab-runner/spack-stage/spack-stage-font-util-1.3.2-c2kz57gaz5zbahmxlya7ys52gttfuxl3/spack-build-out.txt

==> Warning: Skipping build of fontconfig since font-util failed
==> Warning: Skipping build of root since fontconfig failed
==> Warning: Skipping build of fairsoft-config since root failed
==> Warning: Skipping build of libxft since fontconfig failed
[+] /home/gitlab-runner/PandaSoftware/FairSoft/nov20/source/spack/opt/spack/linux-opensuse_leap15-skylake/gcc-7.5.0/findutils-4.6.0-3rkphg4fvt2igdqrey7sogcwy36ksy4y
[+] /home/gitlab-runner/PandaSoftware/FairSoft/nov20/source/spack/opt/spack/linux-opensuse_leap15-skylake/gcc-7.5.0/py-markupsafe-1.1.1-md3ypau2lzt2mpjpcaqoavl2i5jdtlvf
[+] /home/gitlab-runner/PandaSoftware/FairSoft/nov20/source/spack/opt/spack/linux-opensuse_leap15-skylake/gcc-7.5.0/py-cython-0.29.16-4xaezhbfe7i6v62wm3fwvusoalakjf4c
[+] /home/gitlab-runner/PandaSoftware/FairSoft/nov20/source/spack/opt/spack/linux-opensuse_leap15-skylake/gcc-7.5.0/xrootd-4.12.3-vvmjpbhzo3hcy7tljnjxii7wa4eh2hcx
[+] /home/gitlab-runner/PandaSoftware/FairSoft/nov20/source/spack/opt/spack/linux-opensuse_leap15-skylake/gcc-7.5.0/pythia8-8303-it5tsm42p4k4nbj4notbynp7spoopy26
[+] /home/gitlab-runner/PandaSoftware/FairSoft/nov20/source/spack/opt/spack/linux-opensuse_leap15-skylake/gcc-7.5.0/flex-2.6.4-6byx4ydukjris3td3spyy27seyc7cqzt
[+] /home/gitlab-runner/PandaSoftware/FairSoft/nov20/source/spack/opt/spack/linux-opensuse_leap15-skylake/gcc-7.5.0/py-mako-1.0.4-kmq5i3bbmqqcuffwczcni6x73zqmnvqb
[+] /home/gitlab-runner/PandaSoftware/FairSoft/nov20/source/spack/opt/spack/linux-opensuse_leap15-skylake/gcc-7.5.0/py-numpy-1.19.0-d7wvegfg6qcvaxyrbysvw7ci7r44q3kh
[+] /home/gitlab-runner/PandaSoftware/FairSoft/nov20/source/spack/opt/spack/linux-opensuse_leap15-skylake/gcc-7.5.0/mesa-18.3.6-eyrbbgap4wxe2fzcfmykvvkiffqeszcu
[+] /home/gitlab-runner/PandaSoftware/FairSoft/nov20/source/spack/opt/spack/linux-opensuse_leap15-skylake/gcc-7.5.0/mesa-glu-9.0.1-v66ye4se3oum3ne3iws52hn4ci4ulac5
[+] /home/gitlab-runner/PandaSoftware/FairSoft/nov20/source/spack/opt/spack/linux-opensuse_leap15-skylake/gcc-7.5.0/glew-2.1.0-utsjpyk6wuaqapmydxfb4ocenmkgquy5
[+] /home/gitlab-runner/PandaSoftware/FairSoft/nov20/source/spack/opt/spack/linux-opensuse_leap15-skylake/gcc-7.5.0/ftgl-2.4.0-vhag4h3jbwvdvz5lz3bgbokgolxucodb
==> Error: Installation of fairsoft-config failed.  Review log for details
```

**Comment by ChristianTackeGSI** [comment] 2021-02-23 09:45
Some quick notes:
* We have fixed, and are fixing a bunch of issues with FairSoft spack edition: Please use the dev branch and then an appropriate env. The nov20patches branch was not focussing at all on spack. It was a legacy only release in that sense.
* Our CI for opensuse has some bigger issues. I need to investigate that first.
* After that I will look into your error again.
* That said, I remember some issues about font-util on mac. But yours looks like strange. The macos ones just suddenly went away…
* From the "gitlab-runner", I assume, that you're doing some CI stuff: You might be interested in the `--fail-fast` option of `spack install`. It will stop the build on the first error.

**Comment by TobiasStockmanns** [comment] 2021-02-23 11:09
The problem is also present in the [dev] branch of FairSoft using the [dev] environment of FairSoft.

**Comment by ChristianTackeGSI** [comment] 2021-02-23 11:36
Tjamls for checking that!

**Comment by ChristianTackeGSI** [comment] 2021-02-24 11:27
Okay, small update:
(I know, that doesn't help you!)

Our CI run on opensuse 15.2 works mostly:
* jenkins main entry for last run: https://alfa-ci.gsi.de/blue/organizations/jenkins/FairRootGroup%2FFairSoft/detail/dev/169/pipeline/31
* Full log: https://alfa-ci.gsi.de/blue/rest/organizations/jenkins/pipelines/FairRootGroup/pipelines/FairSoft/branches/dev/runs/169/nodes/31/steps/74/log/?start=0
* That might look like it failed, but looking more carefully at the end of the full log, one notices
  `100% tests passed, 0 tests failed out of 23
`
  It failed, because the upload to CDash failed (which I don't understand yet.)

Summary:
* We can't reproduce your error easily
* Our CI needs repair.
* Now going to look more deeply at your errors.

**Comment by ChristianTackeGSI** [comment] 2021-03-02 11:35
Okay, just happened to stumble over this:
https://github.com/spack/spack/pull/21933
Maybe related?

**Comment by ChristianTackeGSI** [comment] 2021-03-26 15:08
Okay, another thing:

@TobiasStockmanns could you try a `~/.spack/packages.yaml` with this:
```yaml
packages:
  font-util:
    variants: "fonts="
```
(I admit: I haven't yet tested it. But there is a `fonts` variant on font-util and it seems to be the list of fonts it tries to install.)

font-util installs a whole bloat of fonts. And this seems to be a constant source of problems. I just happened to see this on macos.

If this helps, we could consider to not install fonts at all on all our builds. As in "Your systems hopefully has some"

**Comment by dennisklein** [comment] 2021-05-24 22:15
Closing, because abandoned. Re-open, if this is still an issue.

**Closed by dennisklein** 2021-05-24 22:15 UTC
Labels: need-feedback
