### ISSUE TITLE
libzmq broken on MacOS 10.11 in RC_may18

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairSoft#90] opened 2018-05-15 21:30 UTC
I (re)discovered one more problem in `RC_may18`: https://cdash.gsi.de/testDetails.php?test=4334300&build=177668

I already fixed this upstream two weeks ago: https://github.com/zeromq/libzmq/commit/0dda63660e3a8424d954ffc3599fc3390a8722e2

But they have not yet made a release and I forgot to adjust `scripts/package_versions.sh`. I will verify this again tomorrow and update the version accordingly. @MohammadAlTurany Should I just reference the commit hash, or should we fork libzmq and add a tag?

**Comment by dennisklein** [comment] 2018-05-15 21:32
An alternative solution is to revert the `scripts/install_zeromq.sh` back to building via autotools.

**Comment by fuhlig1** [comment] 2018-05-23 08:02
Hi @dennisklein,

I think the issue is fixed. Could you please confirm and close the issue.

**Comment by MohammadAlTurany** [comment] 2018-05-23 08:14
Yes, I think it solved in this [commit](https://github.com/FairRootGroup/FairSoft/commit/de3fc57e549f9e5a2f618f0ae2bf4c28a85a0e45#diff-72347726a4b2d3bed3b204c256585a86)

**Closed** 2018-05-23 08:16 UTC
