### ISSUE TITLE
Linking error on cluster, hbook, h2root, wrong compiler

### ISSUE THREAD

**Issue by ngeraks** [FairRootGroup/FairSoft#439] opened 2021-11-24 08:23 UTC
Dear FairSoft developers,

I am not sure if this issue should be posted here or it is a specifically a ROOT issue.
Please excuse me if not.
Maybe it is a user configuration issue.
I am trying to install FairSoft apr21 in a cluster using a rather old version of gcc,
so I have custom installed gcc-9.3.0, binutils, gsl, xerces-c, cmake, 
I have added them to my bashrc in this manner:
```
export LD_LIBRARY_PATH=$HOME/GCC-9.3.0/lib64:$LD_LIBRARY_PATH  
export PATH=$HOME/GCC-9.3.0/bin:$PATH
```
I then install FairSoft in this legacy manner:
```
cmake -S $work_dir/FairSoft -B $work_dir/FairSoft/build -C $work_dir/FairSoft/FairSoftConfig.cmake    
cmake --build $work_dir/FairSoft/build -j $cpu_threads
```
But I get linking errors related to the c++ standard when compiling root relating to hbook and h2root like so:
```
binutils-2.37/install/bin/ld: CMakeFiles/h2root.dir/src/h2root.cxx.o: in function `convert_1d(int)':  
FairSoft/build/Source/root/main/src/h2root.cxx:474: undefined reference to `__cxa_throw_bad_array_new_length'
```
So this was a weird issue since everything else was just fine. 
After some examination I found an issue in 
```
FairSoft/build/Build/root/hist/hbook/CMakeFiles/HBook.dir/link.txt
```
and
```
FairSoft/build/Build/root/main/CMakeFiles/h2root.dir/link.txt
```
In both of those files my new compiler is used to compile  GCC-9.3.0/bin/g++ 
BUT! for the linking the  old server compiler -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5 is set (by cmake I guess)
After changing to -L/fu/bar/GCC-9.3.0 in both files the compilation/linking finishes normally.

**Comment by dennisklein** [comment] 2021-11-24 16:30
Can you please post `$work_dir/FairSoft/build/CMakeCache.txt`. Also, did you start with a fresh build directory when using the custom gcc 9 installation?

**Comment by dennisklein** [comment] 2021-11-24 16:33
In addition, please also post the file `$work_dir/FairSoft/build/Build/root/CMakeCache.txt`, thx!

**Comment by ngeraks** [comment] 2021-11-24 16:45
`$work_dir/FairSoft/build/CMakeCache.txt`
[CMakeCache1.txt](https://github.com/FairRootGroup/FairSoft/files/7597331/CMakeCache1.txt)
`$work_dir/FairSoft/build/Build/root/CMakeCache.txt`
[CMakeCache2.txt](https://github.com/FairRootGroup/FairSoft/files/7597346/CMakeCache2.txt)
These are after my "fix" (manualy changing link.txt after cmake --build as failed)
I do not see a reference to the server compiler dir here.

**Comment by dennisklein** [comment] 2021-11-24 16:57
Was `$work_dir/FairSoft/build` an empty directory after you set `export PATH=$HOME/GCC-9.3.0/bin:$PATH`, or did you first try with the system gcc. (I don't think CMake can handle changing the compiler for an existing build dir)

**Comment by ngeraks** [comment] 2021-11-24 18:14
I am pretty sure I created a clean build. But to make sure, I rm -rf build just now and rebuilt the process - same issue.

**Comment by dennisklein** [comment] 2021-11-24 19:16
> I do not see a reference to the server compiler dir here.

I agree, the `CMakeCache.txt` files look fine.

> But to make sure, I rm -rf build just now and rebuilt the process - same issue, same fix.

Ok, thx, so far I am out of ideas. Let's see if anyone else gets an idea in the meantime. I will be back from vacation next week and revisit this then.

**Comment by ngeraks** [comment] 2021-11-24 19:57
Maybe it is important to mention that the cmake/legacy.cmake file uses this root configuration:
```
  set(root_version "6.24.06")
  if(APPLE AND CMAKE_VERSION VERSION_GREATER 3.15)
    set(root_builtin_glew "-Dbuiltin_glew=ON")
  endif()
  if(APPLE)
    set(root_cocoa "-Dcocoa=ON")
    set(root_x11 OFF)
  else()
    unset(root_cocoa)
    set(root_x11 ON)
  endif()
  ExternalProject_Add(root
    URL https://root.cern/download/root_v${root_version}.source.tar.gz
    #URL_HASH SHA256=6f061ff6ef8f5ec218a12c4c9ea92665eea116b16e1cd4df4f96f00c078a2f6f
    #PATCH_COMMAND ${patch} -p1 -i "${CMAKE_SOURCE_DIR}/legacy/root/dirty_stdatomic_h_fix.patch"
    ${CMAKE_DEFAULT_ARGS} CMAKE_ARGS
	  "-Dcxx17=ON"
      "-Daqua=ON"
      "-Dasimage=ON"
      "-Dcintex=OFF"
      "-Ddavix=OFF"
      "-Dfortran=ON"
      "-Dgdml=ON"
      "-Dglobus=OFF"
      "-Dgnuinstall=ON"
      "-Dhttp=ON"
	  "-Dgsl_shared=ON"
 	  "-Dbuiltin_gsl=ON"
      "-Dmathmore=ON"
      "-Dminuit2=ON"
      "-Dmlp=ON"
      "-Dpyroot=ON"
      "-Dreflex=OFF"
      "-Droofit=ON"
      "-Drpath=ON"
      "-Dsoversion=ON"
      "-Dspectrum=ON"
      "-Dsqlite=OFF" #was ON
      "-Dtmva=ON"
      "-Dvc=ON"
      "-Dvdt=OFF"
      "-Dvmc=OFF"
      "-Dxml=ON"
      #"-Dxrootd=ON"
	  "-Dbuiltin_xrootd=ON"
	  "-Dbuiltin_zlib=ON"
	  "-Dbuiltin_zstd=ON"
      "-Dx11=${root_x11}"
      ${python}
      ${root_builtin_glew}
      ${root_cocoa}
    DEPENDS pythia6 pythia8 vc ${extract_source_cache_target}
    ${LOG_TO_FILE}
  )
```

**Comment by ChristianTackeGSI** [comment] 2021-12-07 14:22
Okay, just wild guessing.

Maybe we can help cmake to find the correct library?
```shell
export LDFLAGS=-L/foo/GCC-9.3.0/lib
export CMAKE_PREFIX_PATH=/foo/GCC-9.3.0
export CMAKE_LIBRARY_PATH=/foo/GCC-9.3.0/lib
```

I also wonder, why gcc isn't forcing the right paths…

**Comment by ngeraks** [comment] 2021-12-08 22:30
@ChristianTackeGSI Thank you for the suggestion, however, none of those had an effect.
@dennisklein  I just spent some time to create a container and to see the build fail reproduced, only to realize I cannot ship a 31 GB docker container...  and I cannot seem to squash it. (first time docker user)
Would it be reasonable to suggest you to install a 'pure' centos7 container and let you have scripts for the required downloads/installs? 
https://pastebin.com/XTUS4h4G
The first one is the standard setup-centos7
 (I cannot do it on the cluster, so only the bottom is relevant for container) 
 (maybe I missed something)
Along with manual installation of packages

The second file are actually two (should work)
Export previously installed packages and git and build FairSoft
https://pastebin.com/sQgEwK3q

On failure the log should be accessible by
vim /root/fair/FairSoft/build/Log/root-build.log

**Comment by fuhlig1** [comment] 2021-12-09 07:18
@ngeraks, 

after I read your last post and saw that it is about centos7 I wondered if you have the devtoolset8 installed on your system. This comes with a complete toolchain which also includes gcc8. The big advantage of this package is that it comes from RedHat and perfectly integrates into centos7. 
This is the way I installed FairSoft apr21 on the GSI cluster.

**Comment by ngeraks** [comment] 2021-12-09 07:26
@fuhlig1 It seems this package is not installed. Thank you for the suggestion.

**Comment by fuhlig1** [comment] 2021-12-09 07:33
@ngeraks,

Sorry there was a typo it must be devtoolset-8. I checked in our system, there are meanwhile also devtoolset-9, devtoolset-10 and devtoolset-11. 

If none of them is installed, could you convince your admins to install such an additional package on the cluster?

**Comment by ngeraks** [comment] 2021-12-09 08:19
@fuhlig1 I guess maintaining the cluster is the best option, but it seems that would be hiding this glitch rather than solving it.

**Comment by dennisklein** [comment] 2021-12-13 15:23
>  Would it be reasonable to suggest you to install a 'pure' centos7 container and let you have scripts for the required downloads/installs?

Yes. The following worked for me, please compare (especially the environment setup after installing your custom packages):
 
```console
$ singularity --version
singularity version 3.8.0
$ singularity build -f --fix-perms -s centos7 docker://quay.io/centos/centos:7
$ singularity exec -f --no-home -w centos7 bash -l
Singularity> yum -y update
Singularity> yum -y install centos-release-scl
Singularity> yum-config-manager --enable rhel-server-rhscl-7-rpms
Singularity> yum -y install devtoolset-7
Singularity> yum -y install epel-release
Singularity> yum -y groupinstall "C Development Tools and Libraries"
Singularity> yum -y install autoconf automake binutils bison bzip2-devel cmake3 ca-certificates coreutils curl-devel diffutils expat-devel findutils flex gcc-c++ gcc-gfortran gdbm-devel gettext-devel git gperf gsl-devel gzip help2man hostname hwloc-devel m4 make libbsd-devel libtool libicu-devel libunistring-devel libuuid-devel libX11-devel libXau-devel libXdmcp-devel libXext-devel libXfont-devel libXft-devel libxml2-devel libXmu-devel libXpm-devel libXrender-devel lz4-devel make mesa-libGL-devel mesa-libGLU-devel ncurses-devel openssl-devel patch procps protobuf-devel python python-devel readline-devel redhat-lsb-core sed subversion tar tbb-devel unzip wget which xerces-c-devel xz-devel yaml-cpp-devel
Singularity> yum -y clean all
Singularity> 
Singularity> # This enables devtoolset-7 globally!
Singularity> profile="/etc/profile.d/enable-devtoolset-7.sh"
Singularity> cat <<EOF > ${profile}source scl_source enable devtoolset-7
Singularity> EOF
Singularity> chmod a+x "${profile}"
Singularity> 
Singularity> # This enables cmake3 globally!
Singularity> alternatives --install /usr/local/bin/cmake cmake /usr/bin/cmake3 20 --slave /usr/local/bin/ctest ctest /usr/bin/ctest3 --slave /usr/local/bin/cpack cpack /usr/bin/cpack3 --slave /usr/local/bin/ccmake ccmake /usr/bin/ccmake3 --family cmake
Singularity> cd
Singularity> id # fakeroot (singularity argument -f)
uid=0(root) gid=0(root) groups=0(root)
Singularity> pwd
/root
Singularity> yum install gcc
Singularity> yum install vim
Singularity> yum install bzip2
Singularity> yum install texi2html
Singularity> yum install gmp-devel
Singularity> wget https://ftp.gnu.org/gnu/gcc/gcc-9.3.0/gcc-9.3.0.tar.gz
Singularity> tar -xvzf gcc-9.3.0.tar.gz
Singularity> rm -f gcc-9.3.0.tar.gz
Singularity> cd gcc-9.3.0/
Singularity> ./contrib/download_prerequisites
Singularity> ./configure --disable-multilib --prefix /opt/install
Singularity> make -j 36
Singularity> make install
Singularity> cd
Singularity> wget https://mirror.tochlab.net/pub/gnu/binutils/binutils-2.37.tar.gz
Singularity> tar -xvzf binutils-2.37.tar.gz
Singularity> rm -f binutils-2.37.tar.gz
Singularity> cd binutils-2.37
Singularity> ./configure --prefix /opt/install
Singularity> make -j 36
Singularity> make install
Singularity> cd
Singularity> wget https://github.com/Kitware/CMake/releases/download/v3.22.1/cmake-3.22.1.tar.gz
Singularity> tar -xvzf cmake-3.22.1.tar.gz
Singularity> rm -rf cmake-3.22.1.tar.gz
Singularity> cd cmake-3.22.1/
Singularity> ./bootstrap --parallel=36 --prefix=/opt/install
Singularity> make -j 36
Singularity> make install
Singularity> cd
Singularity> wget https://dlcdn.apache.org//xerces/c/3/sources/xerces-c-3.2.3.tar.gz
Singularity> tar -xvzf xerces-c-3.2.3.tar.gz
Singularity> rm -rf xerces-c-3.2.3.tar.gz
Singularity> cd xerces-c-3.2.3/
Singularity> ./configure --prefix=/opt/install
Singularity> make -j 36
Singularity> make install
Singularity> cd
Singularity> wget https://ftp.gnu.org/gnu/gsl/gsl-2.7.1.tar.gz
Singularity> tar -xvzf gsl-2.7.1.tar.gz
Singularity> rm -rf gsl-2.7.1.tar.gz
Singularity> cd gsl-2.7.1/
Singularity> ./configure --prefix=/opt/install
Singularity> make -j36
Singularity> make install
Singularity> # up to here basically what you did except installing everything into the same prefix /opt/install
Singularity> cd
Singularity> export LD_LIBRARY_PATH=/opt/install/lib:/opt/install/lib64:/opt/install/x86_64-pc-linux-gnu/lib:$LD_LIBRARY_PATH  # multiple different lib folders!
Singularity> export PATH=/opt/install/bin:$PATH
Singularity> export CC=/opt/install/bin/gcc
Singularity> export CXX=/opt/install/bin/g++
Singularity> export FC=/opt/install/bin/gfortran # was missing
Singularity> export CMAKE_PREFIX_PATH=/opt/install # since install prefix is non-system, we have to tell CMake where to search for dependencies (gsl, xerces) - (sometimes it is enough to set PATH, depends on the package)
Singularity> git clone -b apr21p1 https://github.com/FairRootGroup/FairSoft
Singularity> cd FairSoft
Singularity> cmake -S. -Bbuild -CFairSoftConfig.cmake
loading initial cache file FairSoftConfig.cmake
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- The Fortran compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/install/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/install/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /opt/install/bin/gfortran - skipped
-- Found Git: /usr/bin/git (found version "1.8.3.1")
-- Found Patch: /usr/bin/patch
-- Found UnixCommands: /usr/bin/bash
--
--   CXX STANDARD       C++17 (change with -DCMAKE_CXX_STANDARD=17)
--
--   BUILD TYPE         RelWithDebInfo (change with -DCMAKE_BUILD_TYPE=...)
--
--   PACKAGE SET        full (change with -DPACKAGE_SET=...)
--
--   PACKAGE              VERSION         OPTION
--   boost                1.75.0
--   clhep                2.4.4.0
--   dds                  3.5.10
--   faircmakemodules     0.2.0
--   fairlogger           1.9.2
--   fairmq               1.4.33
--   flatbuffers          1.12.0
--   fmt                  6.1.2
--   geant3               3-8_fairsoft
--   geant4               10.7.1          single-threaded (change with -DGEANT4MT=ON)
--   geant4_vmc           5-3
--   hepmc                2.06.11
--   odc                  0.18
--   pythia6              428-alice1
--   pythia8              8303
--   root                 6.22.08
--   vc                   1.4.1
--   vgm                  4-8
--   vmc                  1-0-p3
--   zeromq               4.3.2
--
--   SOURCE CACHE       using upstream URLs (generate cache by building target 'source-cache' and pass via -DSOURCE_CACHE=...)
--
--   INSTALL PREFIX     /root/FairSoft/install (change with -DCMAKE_INSTALL_PREFIX=...)
--
--    -> export SIMPATH=/root/FairSoft/install
--
-- Configuring done
-- Generating done
-- Build files have been written to: /root/FairSoft/build
Singularity> cmake --build build --target root -j 36
[  0%] Creating directories for 'vc'
[  0%] Creating directories for 'hepmc'
[  0%] Creating directories for 'pythia6'
[  0%] Performing download step (download, verify and extract) for 'pythia6'
[  0%] Performing download step (download, verify and extract) for 'vc'
[  0%] Performing download step (download, verify and extract) for 'hepmc'
-- hepmc download command succeeded.  See also /root/FairSoft/build/Log/hepmc-download-*.log
[  0%] No update step for 'hepmc'
[  0%] No patch step for 'hepmc'
[  0%] Performing configure step for 'hepmc'
-- vc download command succeeded.  See also /root/FairSoft/build/Log/vc-download-*.log
-- pythia6 download command succeeded.  See also /root/FairSoft/build/Log/pythia6-download-*.log
[  0%] No update step for 'vc'
[  0%] No update step for 'pythia6'
[ 20%] No patch step for 'vc'
[ 20%] Performing patch step for 'pythia6'
-- pythia6 patch command succeeded.  See also /root/FairSoft/build/Log/pythia6-patch-*.log
[ 20%] Performing configure step for 'vc'
[ 20%] Performing configure step for 'pythia6'
-- hepmc configure command succeeded.  See also /root/FairSoft/build/Log/hepmc-configure-*.log
[ 20%] Performing build step for 'hepmc'
-- pythia6 configure command succeeded.  See also /root/FairSoft/build/Log/pythia6-configure-*.log
[ 20%] Performing build step for 'pythia6'
-- hepmc build command succeeded.  See also /root/FairSoft/build/Log/hepmc-build-*.log
[ 40%] Performing install step for 'hepmc'
-- hepmc install command succeeded.  See also /root/FairSoft/build/Log/hepmc-install-*.log
[ 40%] Completed 'hepmc'
[ 40%] Built target hepmc
[ 40%] Creating directories for 'pythia8'
[ 60%] Performing download step (download, verify and extract) for 'pythia8'
-- pythia8 download command succeeded.  See also /root/FairSoft/build/Log/pythia8-download-*.log
[ 60%] No update step for 'pythia8'
[ 60%] No patch step for 'pythia8'
[ 60%] Performing configure step for 'pythia8'
-- pythia8 configure command succeeded.  See also /root/FairSoft/build/Log/pythia8-configure-*.log
[ 60%] Performing build step for 'pythia8'
-- vc configure command succeeded.  See also /root/FairSoft/build/Log/vc-configure-*.log
[ 60%] Performing build step for 'vc'
-- vc build command succeeded.  See also /root/FairSoft/build/Log/vc-build-*.log
[ 60%] Performing install step for 'vc'
-- vc install command succeeded.  See also /root/FairSoft/build/Log/vc-install-*.log
[ 60%] Completed 'vc'
[ 60%] Built target vc
-- pythia8 build command succeeded.  See also /root/FairSoft/build/Log/pythia8-build-*.log
[ 60%] Performing install step for 'pythia8'
-- pythia8 install command succeeded.  See also /root/FairSoft/build/Log/pythia8-install-*.log
[ 60%] Completed 'pythia8'
[ 60%] Built target pythia8
-- pythia6 build command succeeded.  See also /root/FairSoft/build/Log/pythia6-build-*.log
[ 60%] Performing install step for 'pythia6'
-- pythia6 install command succeeded.  See also /root/FairSoft/build/Log/pythia6-install-*.log
[ 80%] Completed 'pythia6'
[ 80%] Built target pythia6
[100%] Creating directories for 'root'
[100%] Performing download step (download, verify and extract) for 'root'
-- root download command succeeded.  See also /root/FairSoft/build/Log/root-download-*.log
[100%] No update step for 'root'
[100%] Performing patch step for 'root'
-- root patch command succeeded.  See also /root/FairSoft/build/Log/root-patch-*.log
[100%] Performing configure step for 'root'
-- root configure command succeeded.  See also /root/FairSoft/build/Log/root-configure-*.log
[100%] Performing build step for 'root'
-- root build command succeeded.  See also /root/FairSoft/build/Log/root-build-*.log
[100%] Performing install step for 'root'
-- root install command succeeded.  See also /root/FairSoft/build/Log/root-install-*.log
[100%] Completed 'root'
[100%] Built target root
```

[root-configure.log](https://github.com/FairRootGroup/FairSoft/files/7704852/root-configure.log)
[root-build.log](https://github.com/FairRootGroup/FairSoft/files/7704854/root-build.log)

**Comment by dennisklein** [comment] 2022-02-22 19:29
Closing because stale. Re-open if the issue is not yet resolved.

**Closed by dennisklein** 2022-02-22 19:29 UTC
Labels: need-feedback:submitter

**Comment by ngeraks** [comment] 2022-05-01 09:24
Thank you for taking a look at this issue, and please excuse my failure to respond!  
  
It seems the issue is either that I have not set FC to the custom gfortran in my bash_profile  
AND/OR because the cluster has a f95 -> gfortran link, so only in these root folders the ld-linker corresponding to f95 gets used, for some weird reason.
  
Making my own f95 link in the custom compiler installation dir seems to fix this.
