### ISSUE TITLE
Can't compile root on CC7 

### ISSUE THREAD

**Issue by Barthelemy** [FairRootGroup/FairSoft#45] opened 2016-04-20 10:18 UTC
My recoonly.conf  

>   compiler=gcc
  debug=no
  optimize=yes
  geant4_download_install_data_automatic=no
  geant4_install_data_from_dir=no
  build_root6=yes
  build_python=no
  install_sim=no
  SIMPATH_INSTALL=$INSTALLDIR

We have the devtoolset 4 enabled. 
Using either dev or master I get 

> *** Compiling root ................ 
> Copied rootconfig.sh ......................
> Configure Root ..........................................
> patching file geom/geom/src/TGeoShape.cxx
> patching file io/io/src/TStreamerInfo.cxx
> Hunk #1 FAILED at 1040.
> 1 out of 1 hunk FAILED -- saving rejects to file io/io/src/TStreamerInfo.cxx.rej
> patching file tree/tree/src/TBranchElement.cxx
> Hunk #1 succeeded at 3171 (offset -2 lines).
> patching file net/netxng/src/TNetXNGFile.cxx
> patching file cmake/modules/FindXROOTD.cmake
> linuxx8664gcc
> -- The C compiler identification is GNU 4.8.5
> -- The CXX compiler identification is GNU 4.8.5
> -- Check for working C compiler: /bin/gcc
> -- Check for working C compiler: /bin/gcc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> RegularExpression::compile(): Nested *?+.
> RegularExpression::compile(): Error in compile.
> CMake Error at /usr/share/cmake/Modules/CMakeParseImplicitLinkInfo.cmake:38 (if):
>   if given arguments:
> 
>     "Change Dir: /home/testbarth/FairSoft/tools/root/build_for_fair/CMakeFiles/CMakeTmp" "MATCHES" "^( *|.*[/\\])(g++|ld|collect2)[^/\\]*( |\$)" "AND" "NOT" "Change Dir: /home/testbarth/FairSoft/tools/root/build_for_fair/CMakeFiles/CMakeTmp" "MATCHES" "collect2 version "
> 
>   Regular expression "^( *|.*[/\])(g++|ld|collect2)[^/\]*( |$)" cannot
>   compile
> Call Stack (most recent call first):
>   /usr/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:77 (CMAKE_PARSE_IMPLICIT_LINK_INFO)
>   /usr/share/cmake/Modules/CMakeTestCCompiler.cmake:75 (CMAKE_DETERMINE_COMPILER_ABI)
>   CMakeLists.txt:5 (project)
> 
> 
> -- Configuring incomplete, errors occurred!
> make: *** No targets specified and no makefile found.  Stop.
> make: *** No rule to make target `install'.  Stop.
> **** Checking libraries in /opt/hackathon-19-04-2016/lib ****
> *** ERROR: root could not be created.
>  create a symbolic linking for  Vc library .... 
> libVc.a not found in lib dirctory 
> *** End installation of external packages with Errors***
>

**Comment by MohammadAlTurany** [comment] 2016-08-05 08:08
Hi,
As I could not reproduce it, I will close it for now!
best,
Mohammad

**Closed by MohammadAlTurany** 2016-08-05 08:08 UTC

**Comment by Barthelemy** [comment] 2016-08-08 07:25
Hi, sure, it was some time ago, it might have gone away!
