### ISSUE TITLE
Geant4 Cmake error with FairSoft on OSX Yosemite..again

### ISSUE THREAD

**Issue by mckunkel** [FairRootGroup/FairSoft#30] opened 2015-10-30 15:53 UTC
Greetings,
Sorry to repost this, but the dev branch worked on one computer, but not another running the same OSX and Xcode.

The Geant4 part of the build is failing.

CMake Error at cmake/Modules/Geant4MacroUtilities.cmake:125 (message):
Value 'c++11' for variable GEANT4_BUILD_CXXSTD is not allowed

It must be selected from the set: c++98 (DEFAULT: c++98)

**Comment by geniejhang** [comment] 2015-11-04 02:41
Hi.

I'm not sure this might be the same problem.
The same thing happened on my system and found out that
even though FairSoft installs new version of CMake, it doesn't use or the environmental variable not properly set to use the new version.
So, the script keeps using the old version of CMake and this caused the problem.

The solution I took is after new version of CMake is installed,
I set the bin directory of FairSoft to PATH environmental variable.
After this remedy, my system passed the part smoothly.

**Comment by fuhlig1** [comment] 2016-01-20 13:14
The problem is that the version string emitted by "clang --version" has changed for XCode 7 which causes the problem. The problem should be fixed in the dev branch and also in jul15_patches and mar15_patches branches. Which branch do you use?

**Closed** 2016-06-03 11:25 UTC
