### ISSUE TITLE
Millepede Build Issues

### ISSUE THREAD

**Issue by janmayer** [FairRootGroup/FairSoft#17] opened 2014-11-19 14:44 UTC
When compiling MillepedeII, the final step in the creation of the `pede` executable fails:

```
*** Downloading MillepedeII sources with subversion***
...
Checked out revision 132.
*** Compiling Millepede ................ 
patching file Makefile
Using gcc version 4.9.1
/usr/bin/gfortran -Wall -fautomatic -fno-backslash -O3 -cpp -fopenmp -DREAD_C_FILES -c mpdef.f90 -o mpdef.o 
/usr/bin/gfortran -Wall -fautomatic -fno-backslash -O3 -cpp -fopenmp -DREAD_C_FILES -c mpdalc.f90 -o mpdalc.o 
/usr/bin/gfortran -Wall -fautomatic -fno-backslash -O3 -cpp -fopenmp -DREAD_C_FILES -c mpmod.f90 -o mpmod.o 
/usr/bin/gfortran -Wall -fautomatic -fno-backslash -O3 -cpp -fopenmp -DREAD_C_FILES -c mpbits.f90 -o mpbits.o 
/usr/bin/gfortran -Wall -fautomatic -fno-backslash -O3 -cpp -fopenmp -DREAD_C_FILES -c mptest1.f90 -o mptest1.o 
/usr/bin/gfortran -Wall -fautomatic -fno-backslash -O3 -cpp -fopenmp -DREAD_C_FILES -c mptest2.f90 -o mptest2.o 
/usr/bin/gfortran -Wall -fautomatic -fno-backslash -O3 -cpp -fopenmp -DREAD_C_FILES -c mille.f90 -o mille.o 
/usr/bin/gfortran -Wall -fautomatic -fno-backslash -O3 -cpp -fopenmp -DREAD_C_FILES -c mpnum.f90 -o mpnum.o 
/usr/bin/gfortran -Wall -fautomatic -fno-backslash -O3 -cpp -fopenmp -DREAD_C_FILES -c mptext.f90 -o mptext.o 
/usr/bin/gfortran -Wall -fautomatic -fno-backslash -O3 -cpp -fopenmp -DREAD_C_FILES -c mphistab.f90 -o mphistab.o 
/usr/bin/gfortran -Wall -fautomatic -fno-backslash -O3 -cpp -fopenmp -DREAD_C_FILES -c minresDataModule.f90 -o minresDataModule.o 
/usr/bin/gfortran -Wall -fautomatic -fno-backslash -O3 -cpp -fopenmp -DREAD_C_FILES -c minresModule.f90 -o minresModule.o 
/usr/bin/gfortran -Wall -fautomatic -fno-backslash -O3 -cpp -fopenmp -DREAD_C_FILES -c minresqlpDataModule.f90 -o minresqlpDataModule.o 
/usr/bin/gfortran -Wall -fautomatic -fno-backslash -O3 -cpp -fopenmp -DREAD_C_FILES -c minresqlpBlasModule.f90 -o minresqlpBlasModule.o 
/usr/bin/gfortran -Wall -fautomatic -fno-backslash -O3 -cpp -fopenmp -DREAD_C_FILES -c minresqlpModule.f90 -o minresqlpModule.o 
/usr/bin/gfortran -Wall -fautomatic -fno-backslash -O3 -cpp -fopenmp -DREAD_C_FILES -c randoms.f90 -o randoms.o 
/usr/bin/gfortran -Wall -fautomatic -fno-backslash -O3 -cpp -fopenmp -DREAD_C_FILES -c vertpr.f90 -o vertpr.o 
/usr/bin/gfortran -Wall -fautomatic -fno-backslash -O3 -cpp -fopenmp -DREAD_C_FILES -c linesrch.f90 -o linesrch.o 
/usr/bin/gfortran -Wall -fautomatic -fno-backslash -O3 -cpp -fopenmp -DREAD_C_FILES -c Dbandmatrix.f90 -o Dbandmatrix.o 
/usr/bin/gfortran -Wall -fautomatic -fno-backslash -O3 -cpp -fopenmp -DREAD_C_FILES -c pede.f90 -o pede.o 
gcc  -c -Wall -O3 -Df2cFortran -DUSE_ZLIB -I=    -o readc.o readc.c
In file included from readc.c:39:0:
cfortran.h:415:14: warning: ‘c2fstrv’ defined but not used [-Wunused-function]
 static char *c2fstrv(char* cstr, char *fstr, int elem_len, int sizeofcstr)
              ^
cfortran.h:432:14: warning: ‘f2cstrv’ defined but not used [-Wunused-function]
 static char *f2cstrv(char *fstr, char* cstr, int elem_len, int sizeofcstr)
              ^
cfortran.h:479:14: warning: ‘vkill_trailing’ defined but not used [-Wunused-function]
 static char *vkill_trailing(char* cstr, int elem_len, int sizeofcstr, char t)
              ^
cfortran.h:522:12: warning: ‘num_elem’ defined but not used [-Wunused-function]
 static int num_elem(char *strv, unsigned elem_len, int term_char, int num_term)
            ^
gcc -Wall -O3 \
		-o pede mpdef.o mpdalc.o mpmod.o mpbits.o mptest1.o mptest2.o mille.o mpnum.o mptext.o mphistab.o minresDataModule.o minresModule.o minresqlpDataModule.o minresqlpBlasModule.o minresqlpModule.o randoms.o vertpr.o linesrch.o Dbandmatrix.o pede.o readc.o -lgfortran -lm -lgomp -L= -lz 
/usr/lib/../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
make: *** [pede] Error 1
```

This error seems to be introduced by `Makefile_millipede.patch`, which changes the compiler for the fortran files:
``` diff
-FCOMP = $(OMPP) $(GCC)
+FCOMP = $(OMPP) $(FC)
```
The final step (involving the `LOADER`) should then be changed accordingly. Here is a patch for the patch:
``` diff
From ae7bcba75c3d755d62bc9b9ad25d126f3ec6e27b Mon Sep 17 00:00:00 2001
From: Jan Mayer <jan.mayer@ikp.uni-koeln.de>
Date: Wed, 19 Nov 2014 15:38:53 +0100
Subject: [PATCH] Use FC when building pede in MillepedeII

---
 basics/Makefile_millepede.patch |    2 +-
 1 files changed, 1 insertions(+), 1 deletions(-)

diff --git a/basics/Makefile_millepede.patch b/basics/Makefile_millepede.patch
index 9da2ab2..855dac8 100644
--- a/basics/Makefile_millepede.patch
+++ b/basics/Makefile_millepede.patch
@@ -18,7 +18,7 @@
  endif
  #
 -LOADER = $(OMPP) $(GCC)
-+LOADER = $(OMPP) $(CC)
++LOADER = $(OMPP) $(FC)
  L_FLAGS = -Wall -O3
  #
  # objects for this project
-- 
1.7.1

```

**Comment by fuhlig1** [comment] 2015-03-20 11:23
Hi,

sorry for the very late respons. I though I have answered the issue already month ago. I tested at that time and I tested now again.

I could not reproduce your error on any of the tested platforms which are 

Mac OSX: 10.10, 10.9 and 10.6

Fedora: 19, 20 and 21 (all 64bit)
OpenSuse: 12.3, 13.1, 13.2 (all 64bit)
SLC: 6 (64bit)
Ubuntu: 13.10, 14.04, 14.10 (64bit) und 14.04 (32bit)
Debian; 6, 7, 8 (all 64bit)

I will close the issue now. If the problem is still there please create anew issue and report the exact OS you are using, so that I can try to reproduce the problem.

Ciao

Florian

**Closed by fuhlig1** 2015-03-20 11:23 UTC
