### ISSUE TITLE
boost download location

### ISSUE THREAD

**Issue by ngeraks** [FairRootGroup/FairSoft#404] opened 2021-05-15 06:20 UTC
FairSoft master branch legacy install

-- Using src='https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.bz2'
-- [download 0% complete]
CMake Error at /opt/buildFS/Stamp/boost/download-boost.cmake:170 (message):
  Each download failed!

    error: downloading 'https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.bz2' failed
          status_code: 22
          status_string: "HTTP response code said error"

Fixed by:
cmake/legacy.cmake
 URL "https://boostorg.jfrog.io/artifactory/main/release/1.${boost_version}.0/source/boost_1_${boost_version}_0.tar.gz"

**Comment by fuhlig1** [comment] 2021-05-17 07:34
Hi,

the issue is fixed in the dev branch as well as in the branches nov20_patches and apr21_patches. Could you use one of these branches till the issue is fixed in master?

**Comment by ngeraks** [comment] 2021-05-17 07:38
Thank you! I did not realize it is already fixed in the newer versions! Please close the issue.

**Closed** 2021-05-17 07:39 UTC

**Comment by dennisklein** [comment] 2021-05-17 13:44
That was actually an oversight on my side, `apr21` is the latest release, so `master` should track `apr21_patches` as [documented](https://github.com/FairRootGroup/FairSoft/blob/master/legacy/README.md#2-clone-the-git-repo). I have updated the `master` branch now!
