### ISSUE TITLE
Issues with installing FairSoft on Ubuntu 20.04.6 LTS

### ISSUE THREAD

**Issue by hasandarwish** [FairRootGroup/FairSoft#539] opened 2024-05-16 18:49 UTC
Dear experts,

Please bear with me as I am a complete beginner.

I am having an issue installing FairSoft (Legacy) on Ubuntu 20.04.6 LTS.
I think that I followed the instructions step by step and I installed the required packages.
But I am getting an error in the step **cmake --build <path-to-build> [-j<ncpus>]**

The output in the terminal is in the file:
[log_fairsoft_cmake_build.log](https://github.com/FairRootGroup/FairSoft/files/15339084/log_fairsoft_cmake_build.log)

The mentioned file name with "see also" is here:
[root-build.log](https://github.com/FairRootGroup/FairSoft/files/15339096/root-build.log)

I tried the solution suggested in https://github.com/FairRootGroup/FairSoft/issues/538
But I got the same errors as well as an additional error shown here: 
[error_after_solution.txt](https://github.com/FairRootGroup/FairSoft/files/15339668/error_after_solution.txt)

Thank you for your help!

**Comment by fuhlig1** [comment] 2024-05-17 06:51
Hi Hasan,

which version of FairSoft do you try to install? Did you use the master branch or one of the tagged versions?

Ciao

Florian

**Comment by hasandarwish** [comment] 2024-05-17 08:00
Hi,

I tried: jan24, jan24_patches and nov22p1.

The three of them didn't work.

**Comment by fuhlig1** [comment] 2024-05-17 08:42
Did you install all the necessary dependencies? You can find scripts for various systems in the legacy folder, in your case the script is setup-ubuntu.sh.

**Comment by hasandarwish** [comment] 2024-05-17 08:45
Yes I did run this script and it worked properly.

**Comment by fuhlig1** [comment] 2024-05-17 08:56
Thanks for confirmation. I will try to try an installation on Ubuntu 20.04 myself to see if I can reproduce the problem.

**Comment by fuhlig1** [comment] 2024-05-29 07:13
Sorry but I didn't find the time to do the test yet.

**Comment by hasandarwish** [comment] 2024-06-24 14:38
Dear Florian,

Did you finally have time to check for this?

**Comment by fuhlig1** [comment] 2024-07-03 08:52
Hi @hasandarwish,

finally I managed to test the compilation myself. For me the compilation of FairSoft nov22p1 worked without any problems.
I started with a minimal ubuntu system (20.04.6 LTS (Focal Fossa)), cloned the FairSoft repository and did a checkout of the version nov22p1.
I used the script `legacy/setup-ubuntu.sh` from the FairSoft source to install all dependencies.
Since the CMake version  of the system is to old I installed a proper version using the `bootstrap-cmake.sh` script.
Finally I generated the CMake configuration and build Fairsoft

```
cmake -S . -B build -DCMAKE_CXX_STANDARD=17 
cmake --build build -j96
```
Is it possible that you remove all FairSoft installation from your machine and to start from scratch following the few steps I described in the issue?

Ciao

Florian

**Comment by hasandarwish** [comment] 2024-07-03 12:13
Hi Florian,


I tried exactly what you suggested and I got the following errors shown in the attached file:
[fairsoft_errors.txt](https://github.com/user-attachments/files/16084354/fairsoft_errors.txt)




Regards,


Hasan

**Comment by fuhlig1** [comment] 2024-07-03 12:16
Hi @hasandarwish,

Please try with the nov22_patches branch which fixes the changed hepmc download URL. It is fixed in the branch but no new released was tagged yet. I fixed it manually in my version and forgot to mention it in the issue.

Ciao

Florian

**Comment by dennisklein** [comment] 2024-07-03 13:33
> but no new released was tagged yet.

Just landed: https://github.com/FairRootGroup/FairSoft/releases/tag/nov22p2

**Comment by hasandarwish** [comment] 2024-07-03 14:17
Hi Florian,


nov22_patches gave the same error, but I tried jan24_patches and it worked!
I will continue with the FairRoot installation and see how it goes.


Thanks a lot!


Hasan

**Comment by hasandarwish** [comment] 2024-07-03 14:39
Hi again,


Please excuse me and bear with me.
I am trying now to install FairRoot.
While doing: `cmake -DCMAKE_INSTALL_PREFIX="/home/hdarwish/Softwares/FairRoot/install" ..`
I am getting the following on the terminal:
------------------------------------------------------------
hdarwish@l5420:~/Softwares/FairRoot/build$ cmake -DCMAKE_INSTALL_PREFIX="/home/hdarwish/Softwares/FairRoot/install" ..
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
--- Found a Linux system
--- Found GNU compiler collection
-- Looking for IWYU... - Not found
CMake Error at /opt/cmake-3.29.3-linux-x86_64/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR filesystem serialization
  program_options container date_time regex) (Required is at least version
  "1.67")
Call Stack (most recent call first):
  /opt/cmake-3.29.3-linux-x86_64/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /opt/cmake-3.29.3-linux-x86_64/share/cmake-3.29/Modules/FindBoost.cmake:2393 (find_package_handle_standard_args)
  /usr/local/share/faircmakemodules/modules/FairFindPackage2.cmake:214 (find_package)
  CMakeLists.txt:233 (find_package2)


-- Configuring incomplete, errors occurred!
---------------------------------------------------------------

Can you please help me?


Hasan

**Comment by fuhlig1** [comment] 2024-07-03 14:47
Did the FairSoft compilation finish without errors?

Did you do 

export SIMPATH=<your FairSoft installation>

**Comment by hasandarwish** [comment] 2024-07-03 15:02
Yes, FairSoft compiled successfully without errors, as I said in the second previous message (with jan24_patches).

But FairRoot gave the errors shown in the previous message.

**Comment by hasandarwish** [comment] 2024-08-28 14:17
Hi Florian,

Can you please give me some time and have a look on what I am getting?
I successfully installed FairSoft and I am trying now to install FairRoot.
While doing: cmake -DCMAKE_INSTALL_PREFIX="$SIMPATH" -DBoost_INCLUDE_DIR=/usr/include/ ..

I am getting the following on the terminal:
`hdarwish@l5420:~/Softwares/FairRoot/build$ cmake -DCMAKE_INSTALL_PREFIX="$SIMPATH" -DBoost_INCLUDE_DIR=/usr/include/ ..
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
--- Found a Linux system
--- Found GNU compiler collection
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
CMake Error at /opt/cmake-3.29.3-linux-x86_64/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: filesystem serialization program_options
  container date_time regex) (found suitable version "1.71.0", minimum
  required is "1.67")
Call Stack (most recent call first):
  /opt/cmake-3.29.3-linux-x86_64/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /opt/cmake-3.29.3-linux-x86_64/share/cmake-3.29/Modules/FindBoost.cmake:2393 (find_package_handle_standard_args)
  /usr/local/share/faircmakemodules/modules/FairFindPackage2.cmake:214 (find_package)
  CMakeLists.txt:236 (find_package2)


-- Configuring incomplete, errors occurred!
`


Thank you for your time.
Best regards,


Hasan

**Comment by fuhlig1** [comment] 2024-08-29 06:56
@hasandarwish,

I wonder about your cmake command line and why you define the location of boost. FairSoft includes the proper version of boost such that you don't need a system one. Beside this in my opinion you shouldn't install FairRoot in the same location where FairSoft is installed, but in principle this should work.

To install FairRoot you normally only need to define the SIMPATH and CMake will detect all necessary packages automatically. 

```
export SIMPATH=<Path to your FairSoft installation>
cmake -DCMAKE_INSTALL_PREFIX=<Path to where to install FairRoot>
```

**Comment by hasandarwish** [comment] 2024-08-29 07:18
Hi,

Thanks for your reply.
Although I have boost version 1.71, it asks for minimum of 1.67!
It still gives similar error:

> hdarwish@l5420:~/Softwares/FairRoot/build$ cmake -DCMAKE_INSTALL_PREFIX=/home/hdarwish/Softwares/FairRoot ..
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
--- Found a Linux system
--- Found GNU compiler collection
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
CMake Error at /opt/cmake-3.29.3-linux-x86_64/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR filesystem serialization
  program_options container date_time regex) (Required is at least version
  "1.67")
Call Stack (most recent call first):
  /opt/cmake-3.29.3-linux-x86_64/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /opt/cmake-3.29.3-linux-x86_64/share/cmake-3.29/Modules/FindBoost.cmake:2393 (find_package_handle_standard_args)
  /usr/local/share/faircmakemodules/modules/FairFindPackage2.cmake:214 (find_package)
  CMakeLists.txt:236 (find_package2)


-- Configuring incomplete, errors occurred!

**Comment by dennisklein** [comment] 2024-08-29 08:53
1.
> ```
> hdarwish@l5420:~/Softwares/FairRoot/build$ cmake -DCMAKE_INSTALL_PREFIX=/home/hdarwish/Softwares/FairRoot ..
> ```

Your installation directory is equal to the source directory of FairRoot. That is not a good idea.

2. @fuhlig1 asked you multiple times, if you have set the environment variable `$SIMPATH` pointing to the installation directory of FairSoft in the shell instance in which you run the FairRoot cmake commands. This environment variable is critical as this is the way to tell the FairRoot build system where all the build dependencies are located. [Boost is shipped as part of FairSoft](https://github.com/FairRootGroup/FairSoft/blob/master/legacy/README.md#included-packages). The fact that CMake cannot find Boost means
* either you have not set the `$SIMPATH` correctly, or
* your FairSoft installation was not successful.

Can you please post the output of `ls -l $SIMPATH` here.

**Comment by dennisklein** [comment] 2024-08-29 08:54
3. Point 1 is also important for FairSoft, make sure you have not installed FairSoft into the source directory of FairSoft!

**Comment by hasandarwish** [comment] 2024-08-29 09:03
I am sorry but I didn't totally understand.
The output of ls -l $SIMPATH is :

> hdarwish@l5420:~/Softwares$ ls -l $SIMPATH
total 16
drwxr-xr-x  2 hdarwish hdarwish 4096 Aug 23  2023 bin
drwxr-xr-x  3 hdarwish hdarwish 4096 Aug 23  2023 doc
drwxr-xr-x  4 hdarwish hdarwish 4096 Aug 23  2023 man
drwxr-xr-x 10 hdarwish hdarwish 4096 Aug 23  2023 share

and my softwares directory looks like this:

> hdarwish@l5420:~/Softwares$ ls
allpix-squared         genymotion                    SRIM
corry                  json-3.11.3                   taf_M21
FairRoot               json.hpp                      taf-mimosis.zip
FairSoft               log_fairsoft_cmake_build.log  tutorials
FairSoft-build         oliver_corry                  wine-3.0
FairSoft-install       oliver_corry_M21              xrootd
geant4                 ROOT
geant4-v10.7.0.tar.gz  setup-ubuntu.sh

**Comment by dennisklein** [comment] 2024-08-29 09:17
Please start with a fresh FairSoft installation. Do not re-use the existing build and installation directories. Either delete them or choose different ones.

**Comment by hasandarwish** [comment] 2024-08-29 09:19
Is the organization of the fairsoft directories proper like this?
Inside Softwares folder I should have FairSoft, FairSoft-build and FairSoft-install?

**Comment by dennisklein** [comment] 2024-08-29 09:20
The names are arbitrary, but yes, you should always have separate source, build and installation directories.

**Comment by hasandarwish** [comment] 2024-09-02 08:51
Hi,

I reinstalled FairSoft and got the same error in FairRoot cmake again:

> hdarwish@l5420:~/Softwares/FairRoot/build$ cmake -DCMAKE_INSTALL_PREFIX="/home/hdarwish/Softwares/FairRoot/install" ..
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
--- Found a Linux system
--- Found GNU compiler collection
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
CMake Error at /home/hdarwish/Softwares/FairSoft-install/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR filesystem serialization
  program_options container date_time regex) (Required is at least version
  "1.67")
Call Stack (most recent call first):
  /home/hdarwish/Softwares/FairSoft-install/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /home/hdarwish/Softwares/FairSoft-install/share/cmake-3.27/Modules/FindBoost.cmake:2378 (find_package_handle_standard_args)
  /usr/local/share/faircmakemodules/modules/FairFindPackage2.cmake:214 (find_package)
  CMakeLists.txt:236 (find_package2)


-- Configuring incomplete, errors occurred!

**Comment by hasandarwish** [comment] 2024-09-02 08:52
o I have to have an "install" directory in FairRoot folder or it is created automatically after cmake..?

**Comment by fuhlig1** [comment] 2024-09-05 06:52
@hasandarwish,

after testing several different versions of FairSoft and FairRoot I now could reproduce your problem on Ubuntu 20.04.6. 
By accident I forgot to set the SIMPATH when testing the combination FairSoft jan24p3 and FairRoot v19.0.0 which results in the reported error message.

In my opinion you did not set the SIMPATH variable correctly. If I don't define the SIMPATH or define it wrongly I get exactly the described error

```
$ /opt/fairsoft/jan24p3/bin/cmake -S . -B build_test -DCMAKE_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=/opt/fairroot/test
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
--- Found a Linux system
--- Found GNU compiler collection
-- Looking for IWYU... - Not found
CMake Error at /opt/fairsoft/jan24p3/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR filesystem serialization
  program_options container date_time regex) (Required is at least version
  "1.67")
Call Stack (most recent call first):
  /opt/fairsoft/jan24p3/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /opt/fairsoft/jan24p3/share/cmake-3.27/Modules/FindBoost.cmake:2378 (find_package_handle_standard_args)
  /opt/fairsoft/jan24p3/share/faircmakemodules/modules/FairFindPackage2.cmake:214 (find_package)
  CMakeLists.txt:233 (find_package2)
```

If I define the correct SIMPATH the configuration runs without problems. For the check I didn't export the variable but set it on the command line.

```
$ SIMPATH=/opt/fairsoft/jan24p3 /opt/fairsoft/jan24p3/bin/cmake -S . -B build_test -DCMAKE_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=/opt/fairroot/test
--- Found a Linux system
--- Found GNU compiler collection
-- Looking for IWYU... - Not found
-- Performing Test HAVE_FLAG__ffile_prefix_map__opt_fairroot_source_v19_third_party_Catch2_v3_5_4__
-- Performing Test HAVE_FLAG__ffile_prefix_map__opt_fairroot_source_v19_third_party_Catch2_v3_5_4__ - Success
--   
--   INSTALL PREFIX       /opt/fairroot/test (change with -DCMAKE_INSTALL_PREFIX=...)
--   
--   GLOBAL CXX STANDARD  c++17
--   
--   BUILD TYPE           CXX FLAGS
-- * RELWITHDEBINFO       -Wshadow -Wall -O2 -g
--   NIGHTLY              -Wshadow -Wall -O0 -g
--   TEST                 -Wshadow -Wall -O2 -g
--   RELEASE              -Wshadow -Wall -O2
--   DEBUG                -Wshadow -Wall -g
--   DEBUGFULL            -Wshadow -Wall -g3 -fno-inline -Wnon-virtual-dtor -Wno-long-long -ansi -Wundef -Wcast-align -Wchar-subscripts -W -Wpointer-arith -Wformat-security -fno-exceptions -fno-check-new -fno-common -fexceptions
--   PROFILE              -Wshadow -Wall -g3 -fno-inline -ftest-coverage -fprofile-arcs -Wextra -Wunused-variable
--   ARRAY_CHECK          -Wshadow -Wall -g3 -fno-inline -ftest-coverage -fprofile-arcs -fstack-protector
--   
--   (Change the build type with -DCMAKE_BUILD_TYPE=...)
--   
--   DEPENDENCY FOUND     VERSION                   PREFIX
--   FairCMakeModules     1.0.0 (>= 0.2)            /opt/fairsoft/jan24p3
--   ROOT                 6.30.08 (>= 6.18.00)      
--   VMC                  2.0.0                     /opt/fairsoft/jan24p3/include
--   Pythia6              unknown                   /opt/fairsoft/jan24p3
--   Pythia8              8.310                     /opt/fairsoft/jan24p3
--   Protobuf             3.6.1                     /usr
--   Flatbuffers          23.5.26                   /opt/fairsoft/jan24p3
--   Geant3               4.2.0                     /opt/fairsoft/jan24p3
--                                           G3SYS: Geant3_SYSTEM_DIR-NOTFOUND
--   Geant4               11.2.0                    /opt/fairsoft/jan24p3
--                                 G4NEUTRONHPDATA: /opt/fairsoft/jan24p3/share/Geant4/data/G4NDL4.7
--                                        G4LEDATA: /opt/fairsoft/jan24p3/share/Geant4/data/G4EMLOW8.5
--                                G4LEVELGAMMADATA: /opt/fairsoft/jan24p3/share/Geant4/data/PhotonEvaporation5.7
--                               G4RADIOACTIVEDATA: /opt/fairsoft/jan24p3/share/Geant4/data/RadioactiveDecay5.6
--                                G4PARTICLEXSDATA: /opt/fairsoft/jan24p3/share/Geant4/data/G4PARTICLEXS4.0
--                                       G4PIIDATA: /opt/fairsoft/jan24p3/share/Geant4/data/G4PII1.3
--                               G4REALSURFACEDATA: /opt/fairsoft/jan24p3/share/Geant4/data/RealSurface2.2
--                                    G4SAIDXSDATA: /opt/fairsoft/jan24p3/share/Geant4/data/G4SAIDDATA2.0
--                                      G4ABLADATA: /opt/fairsoft/jan24p3/share/Geant4/data/G4ABLA3.3
--                                      G4INCLDATA: /opt/fairsoft/jan24p3/share/Geant4/data/G4INCL1.2
--                                G4ENSDFSTATEDATA: /opt/fairsoft/jan24p3/share/Geant4/data/G4ENSDFSTATE2.3
--   VGM                  5.1.0                     /opt/fairsoft/jan24p3
--   Geant4VMC            6.5.0                     /opt/fairsoft/jan24p3
--   GSL                  unknown                   /usr
--   FairMQ               1.8.4 (>= 1.4.0)          /opt/fairsoft/jan24p3
--   FairLogger           1.11.1 (>= 1.6.0)         /opt/fairsoft/jan24p3
--   fmt                  10.1.1 (>= 5.3.0)         /opt/fairsoft/jan24p3
--   Boost                1.83 (>= 1.67)            /opt/fairsoft/jan24p3
--   yaml-cpp             0.6.2                     /
--   Threads              unknown                   
--   
--   COMPONENT           BUILT?  INFO
--   Examples             YES    (default, disable with -DBUILD_EXAMPLES=OFF)
--   Doxygen              NO     (default, enable with -DBUILD_DOXYGEN=ON)
--   
-- Configuring done (0.9s)
-- Generating done (0.4s)
-- Build files have been written to: /opt/fairroot/source/v19/build_test
```

Please try to check again if you pass the correct SIMPATH when runing CMake.

**Comment by hasandarwish** [comment] 2024-09-06 12:17
Hello Florian,


Thanks a lot for your help and effort!
I failed in setting the correct SIMPATH and it gave the same error again.
However when I copied your command and pasted it with minor paths changes, it worked.

After that, 'make' and 'make install' worked properly.
However, 'make test' failed in 6 tests out of 68.
Is this a problem? Can I proceed in installing the template or do we have to fix these fails first?

**Comment by fuhlig1** [comment] 2024-09-06 12:20
I think the failing tests are no problem now. 4 of them test our templates and their installation, this is nothing to worry about for you. Which two other tests are failing?

**Comment by hasandarwish** [comment] 2024-09-06 12:23
Here is the message at the end:
![Screenshot from 2024-09-06 14-22-38](https://github.com/user-attachments/assets/8a397dad-5a74-4da7-a8cb-c8a1729be656)

**Comment by fuhlig1** [comment] 2024-09-06 12:31
Ok. This are different test than I have expected but for the time being you can ignore them.  The first 5 are related to FairMQ which is nothing you use, at least not to my knowledge. The last one  is one of our new unit tests. Here I have no idea why this one is failing but I will test this on my system.

Anyway in my opinion you can safely proceed.

**Comment by hasandarwish** [comment] 2024-09-06 14:44
Hi, thanks again.
I proceeded into the step of installing the template.
After doing:
> cp  -rf  FairRoot/templates/project_root_containers   MyTest
> cd MyTest
> ./rename.sh  Panda Pnd stt

I am on the `cmake ../Panda` step inside the build directory.
But I can't find any `Panda` directory or file inside MyTest, the file is not created.
It says:
> CMake Error: The source directory "/home/hdarwish/Softwares/MyTest/Panda" does not exist.
There is only PndData and PndGenerators directories inside MyTest

**Comment by fuhlig1** [comment] 2024-09-30 06:57
@hasandarwish,

I close the issue since the original problem was found and solved. The second issue isn't connected to  FairSoft but FairRoot. Please open an issue in the FairRoot project if the problem still persist.

**Closed by fuhlig1** 2024-09-30 06:57 UTC
