### ISSUE TITLE
--E-- Cannot unpack package hepmc

### ISSUE THREAD

**Issue by rklasen** [FairRootGroup/FairSoft#127] opened 2019-02-26 09:25 UTC
Hi,

when I try to run `./configure.sh` on a fresh Ubuntu, the script fails with the error

> `--E-- Cannot unpack package hepmc`

I tracked the error down to the source package for HepMC, which is here:

http://lcgapp.cern.ch/project/simu/HepMC/download/HepMC-2.06.09.tar.gz

It appears this entire tar archive is empty (as of 26.02.2019, 10:00):

```
hexdump -C HepMC-2.06.09.tar.gz 
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
0046621d
```

I uploaded the last working version of the source file [to my Dropbox](https://www.dropbox.com/s/snwl710y2l0y7ii/HepMC-2.06.09.tar.gz?dl=0), can we include the source in this Repo and change the links?

Best wishes,
Roman

**Comment by rbx** [comment] 2019-02-26 09:38
Duplicate of #126.

**Closed by rbx** 2019-02-26 09:38 UTC
